"""Add time and schedule fields to Task model

Revision ID: 28cfc9ef9ee5
Revises: fc5b8ea92af9
Create Date: 2025-09-20 13:16:38.199386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cfc9ef9ee5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('estimated_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Enum('Low', 'Medium', 'High', 'Urgent', name='task_priority'), nullable=False, server_default='Medium'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('priority')
        batch_op.drop_column('estimated_duration')
        batch_op.drop_column('scheduled_time')
        batch_op.drop_column('scheduled_date')

    # ### end Alembic commands ###
